# Compress
compress_html:
  clippings: all

# Plugins
plugins:
  - jekyll-redirect-from

#SASS
sass:
  style: compact

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
baseurl: /

# Default Markdown Engine
markdown: kramdown

# Site configs
